#!/usr/bin/env node
/**
 * Copies backend rule files that the browser must run identically:
 *   apps-script/ListingRules.gs   -> assets/js/listing-rules.js    (listing checks)
 *   apps-script/ProductOptions.gs -> assets/js/product-options.js  (options / variants)
 * One source each: edit the .gs, then `npm run build`.
 *
 *   node tools/build-shared.js          write the copies
 *   node tools/build-shared.js --check  exit 1 if a copy is stale
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const PAIRS = [
  ['apps-script/ListingRules.gs', 'assets/js/listing-rules.js'],
  ['apps-script/ProductOptions.gs', 'assets/js/product-options.js']
];
const CHECK = process.argv.includes('--check');
let stale = 0;

for (const [src, dest] of PAIRS) {
  const header = '// GENERATED by tools/build-shared.js from ' + src + ' - do not edit here.\n';
  const built = header + fs.readFileSync(path.join(ROOT, src), 'utf8');
  const destPath = path.join(ROOT, dest);
  const existing = fs.existsSync(destPath) ? fs.readFileSync(destPath, 'utf8') : null;
  if (existing === built) continue;
  if (CHECK) {
    console.error(dest + ' is out of date. Run `npm run build`.');
    stale++;
  } else {
    fs.writeFileSync(destPath, built);
    console.log('  built ' + dest);
  }
}
if (CHECK) {
  if (stale) process.exit(1);
  console.log(PAIRS.length + ' shared rule files match their source.');
}
